### ISSUE TITLE
epub rendered very poorly on kobo touch -- sides margins

### ISSUE THREAD

**Issue by esantoro** [sarabander/sicp#14]
Hello,

As of subject, I am trying to read the SICP book on my kobo touch.

Unluckily, pages are rendered in an unfortunate manner: small font, margin on both sides.

Basically, the ePub renders as if it was an html page poorly styled.

My fix has been to convert it to mobi and then back to epub using calibre, but it would be nice to have an epub version that renders just right.

Thanks for your time and dedication,
-- 
Emanuele

**Comment by sarabander** [comment]
Emanuele,

Thanks for letting me know about the rendering problems. I don't have e-book readers besides an Android tablet and PC applications to test the book on. I could guess the problem is that Kobo doesn't support enough of the epub3 standard yet. The file passes epub3 validator and renders fine in Readium (reference implementation of an epub3 reader). 

It would be good to arrive at such structure and style of the file that renders reasonably well on most devices, but still complies fully to epub3. That requires access to more devices. The book has demanding content (MathML, SVG, web fonts), not many devices could handle it yet.

Is your Kobo Touch version 2.0, from the same generation as Glo HD and Aura H20?

Greetings,

Andres

**Comment by esantoro** [comment]
Hello Andres,
Yes, my Kobo is the Touch 2.0 model.

I did not know about the book following the epub3 specification.

I guess this is a problem with the software my reader is running.

I'll close this issue myself then.

Thanks,
-- 
Emanuele

**Comment by sarabander** [comment]
Hello Emanuele,

I tested the epub on a Kobo Aura H20 in a bookstore. Although I didn't notice too much weirdness with font size and margins, the figures look ugly and math renders all wrong. I don't know how recent was the firmware on that device or if upgrading your Touch firmware will help. But even with the latest version, the reading experience might not be very good. 

Regards,
Andres
